# Generated by Django 3.2.9 on 2021-11-21 22:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('election_candidate_name', models.CharField(max_length=350)),
                ('election_candidate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('election_generated_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('election_name', models.CharField(max_length=350)),
                ('election_start', models.DateTimeField()),
                ('election_end', models.DateTimeField()),
                ('election_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('election_position_name', models.CharField(max_length=350)),
                ('election_position_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('election_vote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election')),
                ('election_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.candidates')),
                ('election_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.positions')),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='election_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='election_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.positions'),
        ),
    ]
